In [5]:
%pip install plotly
%pip install cufflinks

Requirement already satisfied: plotly in c:\users\maitreyasapariya\desktop\training\crest-training-\07- python for machine learning & data science\venv\lib\site-packages (6.5.2)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\maitreyasapariya\desktop\training\crest-training-\07- python for machine learning & data science\venv\lib\site-packages (from plotly) (2.16.0)
Requirement already satisfied: packaging in c:\users\maitreyasapariya\desktop\training\crest-training-\07- python for machine learning & data science\venv\lib\site-packages (from plotly) (26.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting cufflinks
  Using cached cufflinks-0.17.3-py3-none-any.whl
Requirement already satisfied: numpy>=1.9.2 in c:\users\maitreyasapariya\desktop\training\crest-training-\07- python for machine learning & data science\venv\lib\site-packages (from cufflinks) (2.4.2)
Requirement already satisfied: pandas>=0.19.2 in c:\users\maitreyasapariya\desktop\training\crest-training-\07- python for machine learning & data science\venv\lib\site-packages (from cufflinks) (3.0.0)
Requirement already satisfied: plotly>=4.1.1 in c:\users\maitreyasapariya\desktop\training\crest-training-\07- python for machine learning & data science\venv\lib\site-packages (from cufflinks) (6.5.2)
Requirement already satisfied: six>=1.9.0 in c:\users\maitreyasapariya\desktop\training\crest-training-\07- python for machine learning & data science\venv\lib\site-packages (from cufflinks) (1.17.0)
Requirement already satisfied: colorlover>=0.2.1 in c:\users\maitreyasapariya\desktop\training\crest-training-\07- python for machine learning & data science\venv\lib\site-packages (from cufflinks) (0.3.0)
Requirement already satisfied: setuptools>=34.4.1 in c:\users\maitreyasapariya\desktop\training\crest-training-\07- python for machine learning & data science\venv\lib\site-packages (from cufflinks) (82.0.0)
Requirement already satisfied: ipython>=5.3.0 in c:\users\maitreyasapariya\desktop\training\crest-training-\07- python for machine learning & data science\venv\lib\site-packages (from cufflinks) (9.10.0)
Collecting ipywidgets>=7.0.0 (from cufflinks)
  Using cached ipywidgets-8.1.8-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: colorama>=0.4.4 in c:\users\maitreyasapariya\desktop\training\crest-training-\07- python for machine learning & data science\venv\lib\site-packages (from ipython>=5.3.0->cufflinks) (0.4.6)
Requirement already satisfied: decorator>=4.3.2 in c:\users\maitreyasapariya\desktop\training\crest-training-\07- python for machine learning & data science\venv\lib\site-packages (from ipython>=5.3.0->cufflinks) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in c:\users\maitreyasapariya\desktop\training\crest-training-\07- python for machine learning & data science\venv\lib\site-packages (from ipython>=5.3.0->cufflinks) (1.1.1)
Requirement already satisfied: jedi>=0.18.1 in c:\users\maitreyasapariya\desktop\training\crest-training-\07- python for machine learning & data science\venv\lib\site-packages (from ipython>=5.3.0->cufflinks) (0.19.2)
Requirement already satisfied: matplotlib-inline>=0.1.5 in c:\users\maitreyasapariya\desktop\training\crest-training-\07- python for machine learning & data science\venv\lib\site-packages (from ipython>=5.3.0->cufflinks) (0.2.1)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\users\maitreyasapariya\desktop\training\crest-training-\07- python for machine learning & data science\venv\lib\site-packages (from ipython>=5.3.0->cufflinks) (3.0.52)
Requirement already satisfied: pygments>=2.11.0 in c:\users\maitreyasapariya\desktop\training\crest-training-\07- python for machine learning & data science\venv\lib\site-packages (from ipython>=5.3.0->cufflinks) (2.19.2)
Requirement already satisfied: stack_data>=0.6.0 in c:\users\maitreyasapariya\desktop\training\crest-training-\07- python for machine learning & data science\venv\lib\site-packages (from ipython>=5.3.0->cufflinks) (0.6.3)
Requirement already satisfied: traitlets>=5.13.0 in c:\users\maitreyasapariya\desktop\training\crest-training-\07- python for machine learning & data science\venv\lib\site-packages (from ipython>=5.3.0->cufflinks) (5.14.3)
Requirement already satisfied: wcwidth in c:\users\maitreyasapariya\desktop\training\crest-training-\07- python for machine learning & data science\venv\lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=5.3.0->cufflinks) (0.6.0)
Requirement already satisfied: comm>=0.1.3 in c:\users\maitreyasapariya\desktop\training\crest-training-\07- python for machine learning & data science\venv\lib\site-packages (from ipywidgets>=7.0.0->cufflinks) (0.2.3)
Requirement already satisfied: widgetsnbextension~=4.0.14 in c:\users\maitreyasapariya\desktop\training\crest-training-\07- python for machine learning & data science\venv\lib\site-packages (from ipywidgets>=7.0.0->cufflinks) (4.0.15)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in c:\users\maitreyasapariya\desktop\training\crest-training-\07- python for machine learning & data science\venv\lib\site-packages (from ipywidgets>=7.0.0->cufflinks) (3.0.16)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\users\maitreyasapariya\desktop\training\crest-training-\07- python for machine learning & data science\venv\lib\site-packages (from jedi>=0.18.1->ipython>=5.3.0->cufflinks) (0.8.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\maitreyasapariya\desktop\training\crest-training-\07- python for machine learning & data science\venv\lib\site-packages (from pandas>=0.19.2->cufflinks) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\maitreyasapariya\desktop\training\crest-training-\07- python for machine learning & data science\venv\lib\site-packages (from pandas>=0.19.2->cufflinks) (2025.3)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\maitreyasapariya\desktop\training\crest-training-\07- python for machine learning & data science\venv\lib\site-packages (from plotly>=4.1.1->cufflinks) (2.16.0)
Requirement already satisfied: packaging in c:\users\maitreyasapariya\desktop\training\crest-training-\07- python for machine learning & data science\venv\lib\site-packages (from plotly>=4.1.1->cufflinks) (26.0)
Requirement already satisfied: executing>=1.2.0 in c:\users\maitreyasapariya\desktop\training\crest-training-\07- python for machine learning & data science\venv\lib\site-packages (from stack_data>=0.6.0->ipython>=5.3.0->cufflinks) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\maitreyasapariya\desktop\training\crest-training-\07- python for machine learning & data science\venv\lib\site-packages (from stack_data>=0.6.0->ipython>=5.3.0->cufflinks) (3.0.1)
Requirement already satisfied: pure-eval in c:\users\maitreyasapariya\desktop\training\crest-training-\07- python for machine learning & data science\venv\lib\site-packages (from stack_data>=0.6.0->ipython>=5.3.0->cufflinks) (0.2.3)
Using cached ipywidgets-8.1.8-py3-none-any.whl (139 kB)
Installing collected packages: ipywidgets, cufflinks

   ---------------------------------------- 0/2 [ipywidgets]
   ---------------------------------------- 0/2 [ipywidgets]
   ---------------------------------------- 0/2 [ipywidgets]
   ---------------------------------------- 0/2 [ipywidgets]
   ---------------------------------------- 0/2 [ipywidgets]
   -------------------- ------------------- 1/2 [cufflinks]
   -------------------- ------------------- 1/2 [cufflinks]
   ---------------------------------------- 2/2 [cufflinks]

Successfully installed cufflinks-0.17.3 ipywidgets-8.1.8
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [6]:
import pandas as pd
import numpy as np
%matplotlib inline

In [7]:
from plotly import __version__
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot

print(__version__) # requires version >= 1.9.0

6.5.2

In [8]:
import cufflinks as cf

In [9]:
# For Notebooks
init_notebook_mode(connected=True)

In [10]:
# For offline use
cf.go_offline()

### Fake Data

In [11]:
df = pd.DataFrame(np.random.randn(100,4),columns='A B C D'.split())

In [12]:
df.head()

          A         B         C         D
0 -0.399305  0.072651  1.231079  0.685976
1  0.955746  1.073237  0.103607  0.073393
2 -0.314391 -0.107602 -0.512988 -1.446150
3  1.698433  0.451574 -0.976779  1.557439
4 -1.108993  2.300725  1.609140  1.444377

In [13]:
df2 = pd.DataFrame({'Category':['A','B','C'],'Values':[32,43,50]})

In [14]:
df2.head()

  Category  Values
0        A      32
1        B      43
2        C      50